version: "3.7"

services:
  frontend:
    build: ./frontend
    ports:
      - "4001:4001"
    command: npm run serve
    working_dir: /app
    user: ${HOST_UID_GID}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  backend:
    build: .
    ports:
      - "4000:4000"
    command: mix phx.server
    working_dir: /app
    user: ${HOST_UID_GID}
    environment:
      MIX_ENV: ${MIX_ENV:-dev}
      PG_USER: "postgres"
      PG_PASSWORD: "postgres"
      PG_HOST: "db"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
