version: "3.7"

services:
  frontend:
    build: ./frontend
    ports:
      - "4001:4001"
    command: npm run serve
    working_dir: /app
    user: ${HOST_UID_GID}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  backend:
    build: .
    ports:
      - "4000:4000"
    command: mix phx.server
    working_dir: /app
    user: ${HOST_UID_GID}
    environment:
      MIX_ENV: ${MIX_ENV:-dev}
      PG_USER: "postgres"
      PG_PASSWORD: "postgres"
      PG_HOST: "db"
    depends_on:
      - db
    volumes:
      - .:/app

  release:
    image: ex_diet:2.0.0
    ports:
      - "4002:4000"
    environment:
      PORT: 4000
      URL_HOST: localhost
      URL_PORT: 4002
      URL_SCHEME: http
      SECRET_KEY_BASE: m4NcRfxYZzAignPAWdzNap0Ljg6SoStDrfecjXTyVB73+LdHMNS6/I145MiRAXe9
      POSTGRES_URL: ecto://postgres:postgres@db/ex_diet-dev?pool_size=10
    user: service:service
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
